<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Fahrtenbuch.Domain/Fahrtenbuch.Domain.csproj" />
    <ProjectReference Include="../Fahrtenbuch.Infrastructure/Fahrtenbuch.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
		<InternalsVisibleTo Include="Fahrtenbuch.Application.Tests" />
	</ItemGroup>

</Project>
